In [185]:
import numpy as np
import pandas as pd

In [186]:
df = pd.read_csv('dataset/titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1       0.0       3   
1              2       NaN       1   
2              3       NaN       3   
3              4       NaN       1   
4              5       0.0       3   
..           ...       ...     ...   
886          887       0.0       2   
887          888       1.0       1   
888          889       0.0       3   
889          890       1.0       1   
890          891       0.0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female   NaN      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282      NaN   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [188]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [189]:
df.drop(['PassengerId','Ticket','Fare','Cabin','Name'] , inplace=True , axis=1)

In [190]:
df

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         NaN       1  female  38.0      1      0        C
2         NaN       3  female   NaN      0      0        S
3         NaN       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female   NaN      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [191]:
df['Survived'].fillna(method='ffill' , inplace=True)

In [192]:
df['Age'].fillna(method='ffill' , inplace=True)

In [193]:
df['Embarked'].fillna(method='ffill' , inplace=True)

In [194]:
df

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         0.0       1  female  38.0      1      0        C
2         0.0       3  female  38.0      0      0        S
3         0.0       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female  19.0      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [195]:
x = df.iloc[:,1:]
x

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  38.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female  19.0      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[891 rows x 6 columns]

In [196]:
y = df.iloc[:,0]
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    float64
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [198]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
tr = ColumnTransformer(transformers=[
    ('t2',OneHotEncoder(drop='first',sparse=False),['Sex','Embarked'])
] , remainder='passthrough')

In [199]:
x1 = tr.fit_transform(x)

In [200]:
x1

array([[ 1.,  0.,  1., ..., 22.,  1.,  0.],
       [ 0.,  0.,  0., ..., 38.,  1.,  0.],
       [ 0.,  0.,  1., ..., 38.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ..., 19.,  1.,  2.],
       [ 1.,  0.,  0., ..., 26.,  0.,  0.],
       [ 1.,  1.,  0., ..., 32.,  0.,  0.]])

In [201]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1 , y , test_size=0.2 ,random_state=2)

In [202]:
x_train

array([[ 1.,  0.,  0., ..., 40.,  0.,  0.],
       [ 0.,  0.,  1., ...,  4.,  1.,  1.],
       [ 1.,  0.,  1., ..., 47.,  0.,  0.],
       ...,
       [ 1.,  0.,  0., ..., 71.,  0.,  0.],
       [ 1.,  0.,  1., ..., 50.,  0.,  0.],
       [ 1.,  0.,  1., ..., 45.,  0.,  0.]])

In [216]:
x_test.shape

(179, 7)

In [204]:
y_train

30     0.0
10     1.0
873    0.0
182    0.0
876    0.0
      ... 
534    0.0
584    0.0
493    0.0
527    0.0
168    0.0
Name: Survived, Length: 712, dtype: float64

In [217]:
y_test.shape

(179,)

In [206]:
from sklearn.tree import DecisionTreeClassifier

In [207]:
dtc = DecisionTreeClassifier()

In [208]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [209]:
y_pred = dtc.predict(x_test)

In [210]:
y_pred

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [211]:
from sklearn.metrics import accuracy_score , confusion_matrix

In [212]:
print("Accuracy matrix =",accuracy_score(y_test,y_pred))

Accuracy matrix = 0.7653631284916201


In [213]:
pd.DataFrame(confusion_matrix(y_test , y_pred)) # if all the values are comes along the diagonal then accuracy is 100%

0   1
0  89  11
1  31  48

In [214]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Decision Tree Prediction'] = y_pred

In [215]:
result

Actual Label  Decision Tree Prediction
707           1.0                       0.0
37            0.0                       0.0
615           1.0                       1.0
169           0.0                       0.0
68            1.0                       0.0
..            ...                       ...
89            0.0                       0.0
80            0.0                       0.0
846           0.0                       0.0
870           0.0                       0.0
251           0.0                       0.0

[179 rows x 2 columns]